Traceback (most recent call last):
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/__setup_conda/lib/python3.8/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# additional imports
import torch_geometric
from torch_geometric.data import Data, Dataset, DataLoader
import torch
import e3nn
import math
from e3nn.nn.models.gate_points_2101 import Network
from e3nn import o3
import dmol
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [3], line 2[0m
[1;32m      1[0m [38;5;66;03m# additional imports[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorch_geometric[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtorch_geometric[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdata[39;00m [38;5;28;01mimport[39;00m Data, Dataset, DataLoader
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorch[39;00m

[0;31mModuleNotFoundError[0m: No module named 'torch_geometric'
ModuleNotFoundError: No module named 'torch_geometric'

